import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ethers } from 'ethers'

import { Card } from '../interfaces';
import CardList from '../components/cardlist';
import CardCreate from '../components/cardcreate';
import EthersClient from '../services/ethersclient';

type Props = {
  cards: Card[],
  currentAccount: string
}

const Home = ({cards, currentAccount}: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Pixel Cards
        </h1>

        <div>
          <CardCreate />
        </div>

        <p>{currentAccount}</p>

        <div className={styles.description}>
          <CardList cards={cards} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export async function getStaticProps() {
  let cards = []
  let cardFromSmartContract
  const ethersClient = new EthersClient('http://localhost:7545')
  const counter = await ethersClient.contract.getCardsCounter()

  for(let index = 0; index < counter; index++) {
    cardFromSmartContract = await ethersClient.contract.cards(index)
    cards.push(
      {
        id: cardFromSmartContract[0].toNumber(),
        name: cardFromSmartContract[1],
        description: cardFromSmartContract[2],
        price: ethers.utils.formatEther(cardFromSmartContract[3])
      }
    )
  }

  return {
    props: {
      cards,
      currentAccount: await ethersClient.getCurrentAccount()
    },
  }
}

export default Home
