import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { ethers } from "ethers"

import { Card } from '../interfaces';
import CardList from '../components/cardlist';
import CardCreate from '../components/cardcreate';

type Props = {
  cards: Card[],
  currentAccount: string
}

const Home = ({cards, currentAccount}: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Pixel Cards
        </h1>

        <div>
          <CardCreate />
        </div>

        <p>{currentAccount}</p>

        <div className={styles.description}>
          <CardList cards={cards} />
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export async function getStaticProps() {
  let cards = []
  const provider = new ethers.providers.JsonRpcProvider('http://localhost:7545')

  const currentAccount = await provider.listAccounts();

  const address = '0xD22a947b83AE7ce6Bf9092431c94C39c68C88002'
  const artifact = require('../build/contracts/CardFactory.json')
  const contract = new ethers.Contract(address, artifact.abi, provider)

  const counter = await contract.getCardsCounter()

  for(let index = 0; index < counter; index++)
    cards.push(await contract.cards[index])

  return {
    props: {
      cards,
      currentAccount
    },
  }
}

export default Home
